### ISSUE TITLE
Ignore URL Patterns (lab4)

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [StellaJung-Student/http-parser#11]
Hi Stella, I would like to work on your repo for lab4. 

Thanks.
Pedro.

**Comment by StellaJung-Student** [comment]
That's great. Thanks

**Comment by StellaJung-Student** [comment]
Please let me know any updates~

**Comment by PedroFonsecaDEV** [comment]
@StellaJung-Student no problem. I'm working on it now. I don't know if I will be able to finish today, but tomorrow will be ready.

**Comment by StellaJung-Student** [comment]
Sounds very good^^ Thank you again~

**Comment by PedroFonsecaDEV** [comment]
Hey @StellaJung-Student.
Follow my repo/branch about lab4:
https://github.com/PedroFonsecaDEV/http-parser/tree/issue-11

I just update your readFiles() logic to implement the new feature. 
I had a good experience while reading and working on your code. I believe we always learn something new when we read someone else code. .I liked the design pattern that you create.

Feel free to reach me if you have some questions. 
(I'm always around our slack channel). 
Thanks.
Pedro

**Comment by StellaJung-Student** [comment]
Thank you Pedro~ I will do and let you know~

**Comment by StellaJung-Student** [comment]
Hello, @PedroFonsecaDEV 
Your task looks great but I just realized that you haven't updated the readme file for your new feature so I updated [here](https://github.com/StellaJung-Student/http-parser/tree/issue-11-fix).
You also may got the notification for it so please check and if you are ok with my change, please go for the next step.

**Comment by PedroFonsecaDEV** [comment]
@StellaJung-Student I always forget the readme. Sorry. Thanks.

**Comment by PedroFonsecaDEV** [comment]
Hey @StellaJung-Student, 

I think now the branches are equal. 

[issue-11](https://github.com/PedroFonsecaDEV/http-parser/tree/issue-11)

Let me know if everything is okay.

Thanks.
Pedro

**Comment by StellaJung-Student** [comment]
Everything looks so good so I merged it to my master, [367104a](https://github.com/StellaJung-Student/http-parser/commit/367104a7f1a23e6cf28465d74a8b481ccae06865)
