### ISSUE TITLE
Add more tests

### ISSUE THREAD

**Issue by fluentinstroll** [StellaJung-Student/http-parser#14]
Hi! I'd like to add some more tests to your app for Lab 8. Maybe in the fileService? Let me know if there's something specific you need to get tested.

**Comment by tpark43** [comment]
@fluentinstroll Thank you, there is // Todo part or if you run the coverage, my percertage is very low.
Please feel free to do what ever you want.

**Comment by StellaJung-Student** [comment]
@fluentinstroll, please feel free to add any part but there is a TODO part that should be improved. Thank you.

**Comment by StellaJung-Student** [comment]
@fluentinstroll Thanks a lot~
