### ISSUE TITLE
Using timeout seemed good, but...

### ISSUE THREAD

**Issue by VietnameZe** [StellaJung-Student/http-parser#4]
Obviously, using 'timeout' for requests helped your program run 'faster'. However, because many requests take longer to get response, therefore many of them get wrong status after all. Run it without 'timeout' still better now, before we can figure out the way to satisfy both speed & accuracy.

**Comment by StellaJung-Student** [comment]
I will check it but also you may fix this one~ By the way, I modified default timeout as 3000ms and it is better now but not sure since there are a lot of unkwown parts.

**Comment by humphd** [comment]
A server that doesn't respond for 3 seconds is essentially "dead" since users will browse away to another site.  Likely upping your timeout value is OK, but I wouldn't go much higher than that.

**Comment by StellaJung-Student** [comment]
Actually, I fixed it in [https://github.com/StellaJung-Student/http-parser/commit/e994906088f0d425c494034e08eece185b455315](url). The request library's default timeout was 120000 so I used the same number and it works well. Do you have any idea if I am wrong?

**Comment by humphd** [comment]
@StellaJung-Student sounds good.

**Comment by StellaJung-Student** [comment]
Thank you for your opinion~
