### ISSUE TITLE
New optional feather

### ISSUE THREAD

**Issue by tianlangwu** [StellaJung-Student/http-parser#6]
I think your project can add a new feather that allows passing multiple file paths to your tools.  I would like to work on it for my OSD600 lab 2 if you consent.

**Comment by StellaJung-Student** [comment]
sure no problem! I love to see your new feature!

**Comment by StellaJung-Student** [comment]
Fixed in [this pull request](https://github.com/StellaJung-Student/http-parser/pull/7)
